language: node_js
node_js:
  - 8
after_script:
  - npm run coveralls
addons:
  apt:
    packages:
      - php5-cli
deploy:
  provider: npm
  email: "131.frodon@cloudyks.org"
  api_key: $NPM_TOKEN 
  on:
    tags: true
